pinballmap/pbm-react

- app/components/LocationCard.js
- app/screens/LocationDetails.js
- app/screens/LocationList.js
- app/screens/Login.js
- app/screens/Map.js
Hope you don't mind me doing PRs for really minor stuff.
As I go through these views, I have lots of thoughts (like, say the location name instead of "location details" and make the telephone number a link). Should I add those thoughts to the spec presentation? I want to keep things organized, and not overwhelm you.
> Two minor style updates

- app/screens/Login.js
- app/screens/SignupLogin.js
>  adjusted horizontal alignment on signuplogin 

- app/screens/LocationDetails.js
Lost a couple small things in the merge. No big deal.
> re-added a couple locationdetails styles

- app/screens/LocationDetails.js
- app/screens/UserProfile.js
Nice! Thanks, Beth. I'm just futzing around here. I'll play around with the if then logic some more.
> added some text to profile page if logged out

- app/screens/FilterMap.js
- app/screens/LocationDetails.js
- app/screens/LocationList.js
- app/screens/Saved.js
Also, I got an error about a missing proptypes variable. One on the filtermap, and one on saved. I removed the proptypes stuff from saved, since that page is mostly placeholder stuff. But for filtermap, I imported proptypes to resolve the error. Not sure if that was the right move. Maybe I messed up the merge last night, and all the proptypes stuff should have been removed from filtermap...
> updated some styles stuffs

- app/screens/FilterMap.js
No idea how this looks on android...
But it's a start on ios
> initial filter style

- app/screens/FAQ.js
- app/screens/LocationDetails.js
- app/screens/Login.js
- app/screens/Signup.js
- app/screens/SignupLogin.js
- app/screens/UserProfile.js
On my android device, when I clicked things like "sign in later" there was NO feedback. I changed those Text links to Buttons, and now they _kinda_ give feedback. It's a small improvement.
> Changed text links to buttons; other misc small changes

- app/components/RemoveMachineModal.js
- app/screens/FindMachine.js
- app/screens/Login.js
- app/screens/MachineDetails.js
- app/screens/Signup.js
- app/screens/UserProfile.js
> keyboard dismiss functionality

- app/components/LocationCard.js
- app/components/RemoveMachineModal.js
- app/screens/FindMachine.js
- app/screens/LocationDetails.js
- app/screens/MachineDetails.js
- app/screens/UserProfile.js
> adjusted margins on locationcard for android

- app/screens/EditLocationDetails.js
- app/screens/LocationDetails.js
I need to check this picker styling in android. We also use a picker on the Filter page.
> initial styling of edit location screen

- app/screens/LocationDetails.js
not totally done, but it's an improvement.
> updated location info style

- app/components/DropDownButton.js
- app/components/SearchBar.js
- app/config/router.js
- app/screens/Map.js
- app/screens/Saved.js
What do you think about this?
Note that font-awesome wasn't loading for the icon, so I had to load it another way, a la
https://github.com/react-native-training/react-native-elements/issues/1005
took me forever to get that right. Seems to be a common issue - and I think it's Expo's fault (and possibly only an iOS problem).
But it may not be completely right. Sometimes people use `await` and `this.setState({ fontLoaded: true });`. See https://docs.expo.io/versions/latest/guides/using-custom-fonts/
>  move get location button from searchbar to map 

- app/screens/Login.js
- app/screens/MachineDetails.js
- app/screens/Signup.js
I think this page could still use some styling improvement. I'll keep thinking about it.
Can you add commas to the "personal high score" number?
> format machine details some more

- app/components/SearchBar.js
- app/screens/MachineDetails.js
- app/screens/RecentActivity.js
I didn't get too deep into android.
That `location-arrow` icon on the map isn't showing up! Haven't figured out why not... even without `fontAwesomeLoaded` it doesn't show up.
> searchbar width for android

- app/screens/Map.js
- app/screens/RecentActivity.js
I didn't add icons to the three submission types that we don't want to include.
Not settled on these icon colors..
> added some icons to the recent activity screen

- app/screens/PasswordReset.js
- app/screens/ResendConfirmation.js
- app/screens/SignupLogin.js
I found a new way to vertically align items in a scrollview. https://stackoverflow.com/a/45739033
But it kind of gimps the scrollview. It's not super scrollable, at least on my device. Sometimes it doesn't scroll when you click and drag, and sometimes it does!
And let me know if I'm off-base with my edits to signuplogin.
> style resend/reset; move enable location services text

- app/components/LocationCard.js
- app/screens/FAQ.js
I had that negative margin, so the container had equal padding on all sides. I've increased the margin, and now the text doesn't seem to get cut off. Not perfectly symmetrical anymore. I might look into this a little more.
> adjust margin on locationcard

- app/screens/FAQ.js
Rapid bus commit. Did I do this linking correct? I removed the {` `} part, and I'm not sure if that was wrong.
> updated FAQ to note expo statistics

- app/components/DrawerMenu.js
- app/screens/FilterMap.js
Very minor. I can do builds without this being merged.
> slight drawer icon adjustment for android

- README.md
Opening this again per https://github.com/bpoore/pbm-react/pull/263#issuecomment-538574464
> correct url for app link in README

- app.json
- app/components/NotLoggedIn.js
- app/index.js
- app/screens/About.js
- app/screens/Events.js
- app/screens/FilterMap.js
- app/screens/LocationDetails.js
- app/screens/LocationList.js
- app/screens/PasswordReset.js
- app/screens/ResendConfirmation.js
- app/screens/Saved.js
- app/screens/Signup.js
- app/screens/SignupLogin.js
Some tweaks I did on the bus yesterday. Still need to check on the login screens.
> Dark mode tweaks

- README.md
Hopefully this is formatted ok. Seems nice to have a version history on here.
> updated readme to include release history

- .expo/settings.json
- app/actions/locations_actions.js
- app/components/Search.js
- app/screens/SignupLogin.js
> Use no_details flag on queries

- README.md
- app.config.js
- app/screens/Blog.js
- app/screens/Contact.js
- app/screens/EditLocationDetails.js
- app/screens/MachineDetails.js
- app/screens/Map.js
- app/screens/Podcast.js
- app/screens/SuggestLocation.js
- app/screens/UserProfile.js
and one commit with some final style clean-up.
> 5.2.7 release info

- README.md
- app.config.js
- app/screens/SignupLogin.js
- package-lock.json
- package.json
Sorry, I shouldn't have committed those before testing. I thought "successful build" meant the app wouldn't crash!
> revert to previous reanimated - let's not be hasty

- app/screens/About.js
PR to resolve repeated API call from About page.
https://github.com/pinballmap/pbm-react/issues/533
> fix: resolve about page repeat api calls

- app/screens/LocationDetails.js
Note that I have **not** tested or build this at all! Just working blind in the code here.
I'm a mostly a web developer but eager to get up to speed locally building/testing if needed.
Let me know if this breaks anything as-is or requires any other changes/tests and I can start learning!
Fixes #545
> (Display `Added:` date for new machines in LocationDetails view

- app/screens/Settings.js
- app/theme-context.js
- app/utils/constants.js
- index.js
Address #566 
Theme settings are now system specified, light, dark as a single setting.
> Simplifying theme settings
